--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-09-26 00:20:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 239811)
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- TOC entry 5279 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


--
-- TOC entry 3 (class 3079 OID 239916)
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- TOC entry 5280 (class 0 OID 0)
-- Dependencies: 3
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- TOC entry 4 (class 3079 OID 239997)
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- TOC entry 5281 (class 0 OID 0)
-- Dependencies: 4
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 240008)
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    email public.citext,
    phone character varying(32),
    full_name character varying(120),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 240017)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 240020)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 240021)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 240024)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 240025)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 240028)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 240029)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 240034)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 240037)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 240038)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 240039)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 240042)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 240043)
-- Name: claim_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.claim_request (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    qr_claim_id uuid NOT NULL,
    ip_hash character varying(64),
    device_fp character varying(128),
    user_agent character varying(200),
    email public.citext,
    phone character varying(32),
    consent boolean NOT NULL,
    result character varying(16) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.claim_request OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 240050)
-- Name: consent_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consent_log (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    scope character varying(64) NOT NULL,
    granted boolean NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.consent_log OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 240055)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 240061)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 240062)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 240065)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 240066)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 240071)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 240072)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 240077)
-- Name: merchant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.merchant (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(120) NOT NULL,
    category character varying(40),
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.merchant OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 240083)
-- Name: onchain_tx; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.onchain_tx (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    kind character varying(20) NOT NULL,
    voucher_type_id uuid,
    to_wallet_id uuid,
    amount bigint NOT NULL,
    nonce bigint,
    gas_price numeric,
    status character varying(16) DEFAULT 'queued'::character varying NOT NULL,
    tx_hash character varying(80),
    last_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.onchain_tx OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 240092)
-- Name: otp_login; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.otp_login (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    email character varying(320),
    phone character varying(32),
    code character varying(6) NOT NULL,
    purpose character varying(32) DEFAULT 'login'::character varying NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 5 NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT otp_login_check CHECK (((email IS NOT NULL) OR (phone IS NOT NULL)))
);


ALTER TABLE public.otp_login OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 240101)
-- Name: policy; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.policy (
    key character varying(64) NOT NULL,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.policy OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 240107)
-- Name: pos_redemption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pos_redemption (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    voucher_type_id uuid NOT NULL,
    wallet_id uuid NOT NULL,
    amount bigint DEFAULT 1 NOT NULL,
    status character varying(16) DEFAULT 'reserved'::character varying NOT NULL,
    pos_terminal character varying(64),
    reserved_at timestamp with time zone DEFAULT now() NOT NULL,
    committed_at timestamp with time zone
);


ALTER TABLE public.pos_redemption OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 240114)
-- Name: pos_terminal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pos_terminal (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    merchant_id uuid NOT NULL,
    code character varying(64) NOT NULL,
    api_key character varying(128) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.pos_terminal OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 240120)
-- Name: pos_terminal_voucher; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pos_terminal_voucher (
    terminal_id uuid NOT NULL,
    voucher_type_id uuid NOT NULL
);


ALTER TABLE public.pos_terminal_voucher OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 240123)
-- Name: qr_claim; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.qr_claim (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    code character varying(64) NOT NULL,
    voucher_type_id uuid NOT NULL,
    event_label character varying(64),
    expires_at timestamp with time zone,
    used_by_user uuid,
    used_at timestamp with time zone,
    status character varying(16) DEFAULT 'new'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT qr_claim_status_check CHECK (((status)::text = ANY (ARRAY[('new'::character varying)::text, ('claimed'::character varying)::text, ('expired'::character varying)::text, ('revoked'::character varying)::text])))
);


ALTER TABLE public.qr_claim OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 240130)
-- Name: voucher_balance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.voucher_balance (
    wallet_id uuid NOT NULL,
    voucher_type_id uuid NOT NULL,
    balance bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL
);


ALTER TABLE public.voucher_balance OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 240136)
-- Name: voucher_transfer_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.voucher_transfer_log (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    from_wallet_id uuid,
    to_wallet_id uuid,
    voucher_type_id uuid NOT NULL,
    amount bigint NOT NULL,
    reason character varying(40) NOT NULL,
    pos_ref character varying(64),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.voucher_transfer_log OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 240141)
-- Name: voucher_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.voucher_type (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    slug character varying(64) NOT NULL,
    name character varying(120) NOT NULL,
    description text,
    erc1155_contract character varying(64) NOT NULL,
    token_id numeric(78,0) NOT NULL,
    max_supply bigint,
    per_user_limit integer DEFAULT 1,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.voucher_type OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 240150)
-- Name: wallet; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    provider character varying(40) NOT NULL,
    provider_ref character varying(128) NOT NULL,
    chain_id integer NOT NULL,
    address bytea NOT NULL,
    exportable boolean DEFAULT false NOT NULL,
    export_status character varying(20) DEFAULT 'not_allowed'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT wallet_address_check CHECK ((octet_length(address) = 20))
);


ALTER TABLE public.wallet OWNER TO postgres;

--
-- TOC entry 4997 (class 2606 OID 240161)
-- Name: app_user app_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_email_key UNIQUE (email);


--
-- TOC entry 4999 (class 2606 OID 240163)
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5004 (class 2606 OID 240165)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 5009 (class 2606 OID 240167)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 5012 (class 2606 OID 240169)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5006 (class 2606 OID 240171)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 5015 (class 2606 OID 240173)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 5017 (class 2606 OID 240175)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 5025 (class 2606 OID 240177)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 5028 (class 2606 OID 240179)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 5019 (class 2606 OID 240181)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5031 (class 2606 OID 240183)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5034 (class 2606 OID 240185)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 5022 (class 2606 OID 240187)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 5036 (class 2606 OID 240189)
-- Name: claim_request claim_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.claim_request
    ADD CONSTRAINT claim_request_pkey PRIMARY KEY (id);


--
-- TOC entry 5040 (class 2606 OID 240191)
-- Name: consent_log consent_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consent_log
    ADD CONSTRAINT consent_log_pkey PRIMARY KEY (id);


--
-- TOC entry 5043 (class 2606 OID 240193)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 5046 (class 2606 OID 240195)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 5048 (class 2606 OID 240197)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 5050 (class 2606 OID 240199)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5053 (class 2606 OID 240201)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5056 (class 2606 OID 240203)
-- Name: merchant merchant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.merchant
    ADD CONSTRAINT merchant_pkey PRIMARY KEY (id);


--
-- TOC entry 5059 (class 2606 OID 240205)
-- Name: onchain_tx onchain_tx_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.onchain_tx
    ADD CONSTRAINT onchain_tx_pkey PRIMARY KEY (id);


--
-- TOC entry 5064 (class 2606 OID 240207)
-- Name: otp_login otp_login_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_login
    ADD CONSTRAINT otp_login_pkey PRIMARY KEY (id);


--
-- TOC entry 5066 (class 2606 OID 240209)
-- Name: policy policy_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.policy
    ADD CONSTRAINT policy_pkey PRIMARY KEY (key);


--
-- TOC entry 5069 (class 2606 OID 240211)
-- Name: pos_redemption pos_redemption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pos_redemption
    ADD CONSTRAINT pos_redemption_pkey PRIMARY KEY (id);


--
-- TOC entry 5071 (class 2606 OID 240213)
-- Name: pos_terminal pos_terminal_api_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pos_terminal
    ADD CONSTRAINT pos_terminal_api_key_key UNIQUE (api_key);


--
-- TOC entry 5073 (class 2606 OID 240215)
-- Name: pos_terminal pos_terminal_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pos_terminal
    ADD CONSTRAINT pos_terminal_code_key UNIQUE (code);


--
-- TOC entry 5075 (class 2606 OID 240217)
-- Name: pos_terminal pos_terminal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pos_terminal
    ADD CONSTRAINT pos_terminal_pkey PRIMARY KEY (id);


--
-- TOC entry 5079 (class 2606 OID 240219)
-- Name: pos_terminal_voucher pos_terminal_voucher_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pos_terminal_voucher
    ADD CONSTRAINT pos_terminal_voucher_pkey PRIMARY KEY (terminal_id, voucher_type_id);


--
-- TOC entry 5082 (class 2606 OID 240221)
-- Name: qr_claim qr_claim_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qr_claim
    ADD CONSTRAINT qr_claim_code_key UNIQUE (code);


--
-- TOC entry 5084 (class 2606 OID 240223)
-- Name: qr_claim qr_claim_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qr_claim
    ADD CONSTRAINT qr_claim_pkey PRIMARY KEY (id);


--
-- TOC entry 5087 (class 2606 OID 240225)
-- Name: voucher_balance voucher_balance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_balance
    ADD CONSTRAINT voucher_balance_pkey PRIMARY KEY (id);


--
-- TOC entry 5091 (class 2606 OID 240227)
-- Name: voucher_transfer_log voucher_transfer_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_transfer_log
    ADD CONSTRAINT voucher_transfer_log_pkey PRIMARY KEY (id);


--
-- TOC entry 5093 (class 2606 OID 240229)
-- Name: voucher_type voucher_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_type
    ADD CONSTRAINT voucher_type_pkey PRIMARY KEY (id);


--
-- TOC entry 5095 (class 2606 OID 240231)
-- Name: voucher_type voucher_type_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_type
    ADD CONSTRAINT voucher_type_slug_key UNIQUE (slug);


--
-- TOC entry 5098 (class 2606 OID 240233)
-- Name: wallet wallet_chain_id_address_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT wallet_chain_id_address_key UNIQUE (chain_id, address);


--
-- TOC entry 5100 (class 2606 OID 240235)
-- Name: wallet wallet_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT wallet_pkey PRIMARY KEY (id);


--
-- TOC entry 5102 (class 2606 OID 240237)
-- Name: wallet wallet_provider_provider_ref_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT wallet_provider_provider_ref_key UNIQUE (provider, provider_ref);


--
-- TOC entry 5002 (class 1259 OID 240238)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 5007 (class 1259 OID 240239)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 5010 (class 1259 OID 240240)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 5013 (class 1259 OID 240241)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 5023 (class 1259 OID 240242)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 5026 (class 1259 OID 240243)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 5029 (class 1259 OID 240244)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 5032 (class 1259 OID 240245)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 5020 (class 1259 OID 240246)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 5041 (class 1259 OID 240247)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 5044 (class 1259 OID 240248)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5051 (class 1259 OID 240249)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5054 (class 1259 OID 240250)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5037 (class 1259 OID 240251)
-- Name: idx_claim_req_email_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_claim_req_email_time ON public.claim_request USING btree (email, created_at);


--
-- TOC entry 5038 (class 1259 OID 240252)
-- Name: idx_claim_req_qr; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_claim_req_qr ON public.claim_request USING btree (qr_claim_id);


--
-- TOC entry 5057 (class 1259 OID 240253)
-- Name: idx_onchain_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_onchain_status ON public.onchain_tx USING btree (status, created_at);


--
-- TOC entry 5060 (class 1259 OID 240254)
-- Name: idx_otp_login_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_otp_login_email ON public.otp_login USING btree (email) WHERE (email IS NOT NULL);


--
-- TOC entry 5061 (class 1259 OID 240255)
-- Name: idx_otp_login_exp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_otp_login_exp ON public.otp_login USING btree (expires_at);


--
-- TOC entry 5062 (class 1259 OID 240256)
-- Name: idx_otp_login_phone; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_otp_login_phone ON public.otp_login USING btree (phone) WHERE (phone IS NOT NULL);


--
-- TOC entry 5067 (class 1259 OID 240257)
-- Name: idx_pos_red_wallet; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pos_red_wallet ON public.pos_redemption USING btree (wallet_id, status);


--
-- TOC entry 5076 (class 1259 OID 240258)
-- Name: idx_ptv_terminal; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ptv_terminal ON public.pos_terminal_voucher USING btree (terminal_id);


--
-- TOC entry 5077 (class 1259 OID 240259)
-- Name: idx_ptv_voucher; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ptv_voucher ON public.pos_terminal_voucher USING btree (voucher_type_id);


--
-- TOC entry 5080 (class 1259 OID 240260)
-- Name: idx_qr_claim_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_qr_claim_active ON public.qr_claim USING btree (status) WHERE ((status)::text = 'new'::text);


--
-- TOC entry 5000 (class 1259 OID 240261)
-- Name: idx_user_email_trgm; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_email_trgm ON public.app_user USING gin (email public.gin_trgm_ops);


--
-- TOC entry 5001 (class 1259 OID 240262)
-- Name: idx_user_phone; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_phone ON public.app_user USING btree (phone);


--
-- TOC entry 5088 (class 1259 OID 240263)
-- Name: idx_vtl_from; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_vtl_from ON public.voucher_transfer_log USING btree (from_wallet_id, voucher_type_id);


--
-- TOC entry 5089 (class 1259 OID 240264)
-- Name: idx_vtl_to; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_vtl_to ON public.voucher_transfer_log USING btree (to_wallet_id, voucher_type_id);


--
-- TOC entry 5096 (class 1259 OID 240265)
-- Name: idx_wallet_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_wallet_user ON public.wallet USING btree (user_id);


--
-- TOC entry 5085 (class 1259 OID 240266)
-- Name: uq_vb_wallet_vt; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_vb_wallet_vt ON public.voucher_balance USING btree (wallet_id, voucher_type_id);


--
-- TOC entry 5103 (class 2606 OID 240267)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5104 (class 2606 OID 240272)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5105 (class 2606 OID 240277)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5106 (class 2606 OID 240282)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5107 (class 2606 OID 240287)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5108 (class 2606 OID 240292)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5109 (class 2606 OID 240297)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5110 (class 2606 OID 240302)
-- Name: claim_request claim_request_qr_claim_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.claim_request
    ADD CONSTRAINT claim_request_qr_claim_id_fkey FOREIGN KEY (qr_claim_id) REFERENCES public.qr_claim(id) ON DELETE CASCADE;


--
-- TOC entry 5111 (class 2606 OID 240307)
-- Name: consent_log consent_log_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consent_log
    ADD CONSTRAINT consent_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


--
-- TOC entry 5112 (class 2606 OID 240312)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5113 (class 2606 OID 240317)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5114 (class 2606 OID 240322)
-- Name: onchain_tx onchain_tx_to_wallet_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.onchain_tx
    ADD CONSTRAINT onchain_tx_to_wallet_id_fkey FOREIGN KEY (to_wallet_id) REFERENCES public.wallet(id) ON DELETE SET NULL;


--
-- TOC entry 5115 (class 2606 OID 240327)
-- Name: onchain_tx onchain_tx_voucher_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.onchain_tx
    ADD CONSTRAINT onchain_tx_voucher_type_id_fkey FOREIGN KEY (voucher_type_id) REFERENCES public.voucher_type(id) ON DELETE SET NULL;


--
-- TOC entry 5116 (class 2606 OID 240332)
-- Name: pos_redemption pos_redemption_voucher_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pos_redemption
    ADD CONSTRAINT pos_redemption_voucher_type_id_fkey FOREIGN KEY (voucher_type_id) REFERENCES public.voucher_type(id) ON DELETE CASCADE;


--
-- TOC entry 5117 (class 2606 OID 240337)
-- Name: pos_redemption pos_redemption_wallet_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pos_redemption
    ADD CONSTRAINT pos_redemption_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.wallet(id) ON DELETE CASCADE;


--
-- TOC entry 5118 (class 2606 OID 240342)
-- Name: pos_terminal pos_terminal_merchant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pos_terminal
    ADD CONSTRAINT pos_terminal_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES public.merchant(id) ON DELETE CASCADE;


--
-- TOC entry 5119 (class 2606 OID 240347)
-- Name: pos_terminal_voucher pos_terminal_voucher_terminal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pos_terminal_voucher
    ADD CONSTRAINT pos_terminal_voucher_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.pos_terminal(id) ON DELETE CASCADE;


--
-- TOC entry 5120 (class 2606 OID 240352)
-- Name: pos_terminal_voucher pos_terminal_voucher_voucher_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pos_terminal_voucher
    ADD CONSTRAINT pos_terminal_voucher_voucher_type_id_fkey FOREIGN KEY (voucher_type_id) REFERENCES public.voucher_type(id) ON DELETE CASCADE;


--
-- TOC entry 5121 (class 2606 OID 240357)
-- Name: qr_claim qr_claim_used_by_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qr_claim
    ADD CONSTRAINT qr_claim_used_by_user_fkey FOREIGN KEY (used_by_user) REFERENCES public.app_user(id);


--
-- TOC entry 5122 (class 2606 OID 240362)
-- Name: qr_claim qr_claim_voucher_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.qr_claim
    ADD CONSTRAINT qr_claim_voucher_type_id_fkey FOREIGN KEY (voucher_type_id) REFERENCES public.voucher_type(id) ON DELETE CASCADE;


--
-- TOC entry 5123 (class 2606 OID 240367)
-- Name: voucher_balance voucher_balance_voucher_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_balance
    ADD CONSTRAINT voucher_balance_voucher_type_id_fkey FOREIGN KEY (voucher_type_id) REFERENCES public.voucher_type(id) ON DELETE CASCADE;


--
-- TOC entry 5124 (class 2606 OID 240372)
-- Name: voucher_balance voucher_balance_wallet_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_balance
    ADD CONSTRAINT voucher_balance_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.wallet(id) ON DELETE CASCADE;


--
-- TOC entry 5125 (class 2606 OID 240377)
-- Name: voucher_transfer_log voucher_transfer_log_from_wallet_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_transfer_log
    ADD CONSTRAINT voucher_transfer_log_from_wallet_id_fkey FOREIGN KEY (from_wallet_id) REFERENCES public.wallet(id) ON DELETE SET NULL;


--
-- TOC entry 5126 (class 2606 OID 240382)
-- Name: voucher_transfer_log voucher_transfer_log_to_wallet_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_transfer_log
    ADD CONSTRAINT voucher_transfer_log_to_wallet_id_fkey FOREIGN KEY (to_wallet_id) REFERENCES public.wallet(id) ON DELETE SET NULL;


--
-- TOC entry 5127 (class 2606 OID 240387)
-- Name: voucher_transfer_log voucher_transfer_log_voucher_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.voucher_transfer_log
    ADD CONSTRAINT voucher_transfer_log_voucher_type_id_fkey FOREIGN KEY (voucher_type_id) REFERENCES public.voucher_type(id) ON DELETE CASCADE;


--
-- TOC entry 5128 (class 2606 OID 240392)
-- Name: wallet wallet_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet
    ADD CONSTRAINT wallet_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;


-- Completed on 2025-09-26 00:20:51

--
-- PostgreSQL database dump complete
--

